
# ===============================
# APPLICATION
# ===============================
spring.application.name=Unsolved
server.port=8080


# ===============================
# DATABASE (H2 - file based)
# ===============================
spring.datasource.url=jdbc:h2:file:./data/unsolved-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# H2 CONSOLE
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console




# ===============================
# SECURITY / JWT (placeholders)
# ===============================
# You will use these when implementing JWT
jwt.secret=0f015219122076e98c24fa050ecf2cd51fbba57674ce22a678ef8f5a2416e903
jwt.expiration=86400000


# ===============================
# LOGGING (DEBUG FRIENDLY)
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
